package io.github.rabitem.outcomemetrics.test;

import io.github.rabitem.outcomemetrics.observation.SloCatalog;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@DisplayName("SloScaffold")
class SloScaffoldTest {

    private static final SloCatalog CATALOG = SloCatalog.of("checkout-success", "refund-latency");

    @Test
    @DisplayName("renders a deterministic Sloth prometheus/v1 document with schema-derived queries")
    void deterministicRendering() {
        final String yaml = scaffold().sloth();

        assertThat(yaml).isEqualTo("""
                # Generated by outcome-metrics SloScaffold (Sloth prometheus/v1).
                # Set each objective before use: Sloth refuses to generate while the
                # placeholder SET_OBJECTIVE_PERCENT is in place.
                version: "prometheus/v1"
                service: "checkout"
                slos:
                  - name: "checkout_success"
                    description: "Outcome SLI for slo=checkout_success (deduplicated: occurrence=first)."
                    objective: SET_OBJECTIVE_PERCENT
                    sli:
                      events:
                        error_query: sum(rate(demo_order_place_seconds_count{slo="checkout_success", occurrence="first", outcome="failure"}[{{.window}}]))
                        total_query: sum(rate(demo_order_place_seconds_count{slo="checkout_success", occurrence="first"}[{{.window}}]))
                    alerting:
                      name: "checkout_success_burn_rate"
                      page_alert:
                        labels:
                          severity: "page"
                      ticket_alert:
                        labels:
                          severity: "ticket"
                  - name: "refund_latency"
                    description: "Outcome SLI for slo=refund_latency (deduplicated: occurrence=first)."
                    objective: SET_OBJECTIVE_PERCENT
                    sli:
                      events:
                        error_query: sum(rate(demo_refund_seconds_count{slo="refund_latency", occurrence="first", channel="web", outcome="failure"}[{{.window}}]))
                        total_query: sum(rate(demo_refund_seconds_count{slo="refund_latency", occurrence="first", channel="web"}[{{.window}}]))
                    alerting:
                      name: "refund_latency_burn_rate"
                      page_alert:
                        labels:
                          severity: "page"
                      ticket_alert:
                        labels:
                          severity: "ticket"
                """);
        assertThat(yaml).isEqualTo(scaffold().sloth());
    }

    @Test
    @DisplayName("emits a non-numeric objective so an unedited skeleton cannot silently deploy")
    void placeholderFailsLoud() {
        final String yaml = scaffold().sloth();

        assertThat(yaml).contains("objective: " + SloScaffold.OBJECTIVE_PLACEHOLDER);
        assertThatThrownBy(() -> Double.parseDouble(SloScaffold.OBJECTIVE_PLACEHOLDER))
                .as("Sloth requires a float objective; the placeholder must never parse as one")
                .isInstanceOf(NumberFormatException.class);
    }

    @Test
    @DisplayName("writes the document to disk, creating parent directories")
    void writesToDisk(@TempDir final Path tempDir) throws Exception {
        final Path target = tempDir.resolve("slo/checkout-slos.yaml");

        scaffold().writeTo(target);

        assertThat(Files.readString(target)).contains("version: \"prometheus/v1\"");
    }

    @Test
    @DisplayName("refuses to build while any declared id is unbound and rejects unknown ids")
    void bindingValidation() {
        assertThatThrownBy(() -> SloScaffold.builder()
                .service("checkout").catalog(CATALOG)
                .bind("checkout-success", "demo_order_place_seconds_count")
                .build())
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("refund_latency")
                .hasMessageContaining("cannot drift from the catalog");
        assertThatThrownBy(() -> SloScaffold.builder()
                .service("checkout").catalog(CATALOG)
                .bind("checkout-typo", "demo_order_place_seconds_count"))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("\"checkout-typo\" is not declared");
    }

    @Test
    @DisplayName("validates builder input")
    void builderValidation() {
        assertThatThrownBy(() -> SloScaffold.builder()
                .bind("checkout-success", "demo_order_place_seconds_count"))
                .isInstanceOf(IllegalStateException.class)
                .hasMessage("set the catalog before binding ids");
        assertThatThrownBy(() -> SloScaffold.builder().catalog(CATALOG)
                .bind("checkout-success", " "))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("meter name must not be blank");
        assertThatThrownBy(() -> SloScaffold.builder().catalog(CATALOG)
                .bind("checkout-success", "demo_order_place_seconds_count", "channel"))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("selector labels must be key, value pairs");
        assertThatThrownBy(() -> SloScaffold.builder().catalog(CATALOG)
                .bind("checkout-success", "demo_order_place_seconds_count", "channel", " "))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("selector label keys and values must not be blank");
        assertThatThrownBy(() -> SloScaffold.builder().service(" "))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("service must not be blank");
        assertThatThrownBy(() -> SloScaffold.builder().catalog(CATALOG).build())
                .isInstanceOf(IllegalStateException.class)
                .hasMessage("service is required");
        assertThatThrownBy(() -> SloScaffold.builder().service("checkout").build())
                .isInstanceOf(IllegalStateException.class)
                .hasMessage("catalog is required");
    }

    private static SloScaffold scaffold() {
        return SloScaffold.builder()
                .service("checkout")
                .catalog(CATALOG)
                .bind("checkout-success", "demo_order_place_seconds_count")
                .bind("refund-latency", "demo_refund_seconds_count", "channel", "web")
                .build();
    }
}
