package io.github.rabitem.outcomemetrics.test;

import io.github.rabitem.outcomemetrics.MetricTagValues;
import io.github.rabitem.outcomemetrics.observation.SloCatalog;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.TreeMap;
import java.util.TreeSet;

/**
 * Generates Sloth SLO skeletons from an {@link SloCatalog} — the inverse of #27's drift detector.
 *
 * <p>Code declares the binding (which SLO ids exist and which meter carries each); the SLO
 * toolchain owns the policy. This generator deletes the boilerplate where drift is born while
 * keeping that split intact: the emitted {@code objective} is the non-numeric placeholder
 * {@value #OBJECTIVE_PLACEHOLDER}, which Sloth's generator rejects — a skeleton pasted into a
 * pipeline without a human setting the objective <em>cannot</em> silently deploy.
 *
 * <p>Queries derive from this library's schema: the total is the deduplicated SLI stream
 * ({@code slo="<id>", occurrence="first"}), the error adds {@code outcome="failure"}. Every
 * catalog id must be bound to a meter — an unbound id fails {@code build()}, so the scaffold and
 * the runtime info gauge (#27) can never disagree about what exists.
 *
 * <p>Output targets the Sloth {@code prometheus/v1} spec. Generate once, set objectives, commit;
 * there is deliberately no golden-file assertion — the committed file legitimately diverges from
 * the generator the moment a human sets policy.
 *
 * <pre>{@code
 * SloScaffold.builder()
 *     .service("checkout")
 *     .catalog(sloCatalog)
 *     .bind("checkout-success", "demo_order_place_seconds_count")
 *     .bind("refund-latency", "demo_refund_seconds_count", "channel", "web")
 *     .build()
 *     .writeTo(Path.of("slo/checkout-slos.yaml"));
 * }</pre>
 *
 * @since 0.1.0
 */
public final class SloScaffold {

    /**
     * Non-numeric objective placeholder. Sloth requires a float here, so generation fails until a
     * human replaces it — the loud-failure property this scaffold guarantees.
     */
    public static final String OBJECTIVE_PLACEHOLDER = "SET_OBJECTIVE_PERCENT";

    private final String service;
    private final Map<String, Binding> bindings;

    private SloScaffold(final String service, final Map<String, Binding> bindings) {
        this.service = service;
        this.bindings = bindings;
    }

    /**
     * Creates a scaffold builder.
     *
     * @return a new builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Renders the Sloth {@code prometheus/v1} document (deterministic: SLOs sorted by id, selector
     * labels sorted, stable across runs).
     *
     * @return the YAML document, never {@code null}
     */
    public String sloth() {
        final StringBuilder yaml = new StringBuilder();
        yaml.append("# Generated by outcome-metrics SloScaffold (Sloth prometheus/v1).\n");
        yaml.append("# Set each objective before use: Sloth refuses to generate while the\n");
        yaml.append("# placeholder ").append(OBJECTIVE_PLACEHOLDER).append(" is in place.\n");
        yaml.append("version: \"prometheus/v1\"\n");
        yaml.append("service: \"").append(service).append("\"\n");
        yaml.append("slos:\n");
        for (final Map.Entry<String, Binding> bound : bindings.entrySet()) {
            final String id = bound.getKey();
            final Binding binding = bound.getValue();
            yaml.append("  - name: \"").append(id).append("\"\n");
            yaml.append("    description: \"Outcome SLI for slo=").append(id)
                    .append(" (deduplicated: occurrence=first).\"\n");
            yaml.append("    objective: ").append(OBJECTIVE_PLACEHOLDER).append('\n');
            yaml.append("    sli:\n");
            yaml.append("      events:\n");
            yaml.append("        error_query: sum(rate(").append(binding.meterName)
                    .append('{').append(selector(id, binding, true)).append("}[{{.window}}]))\n");
            yaml.append("        total_query: sum(rate(").append(binding.meterName)
                    .append('{').append(selector(id, binding, false)).append("}[{{.window}}]))\n");
            yaml.append("    alerting:\n");
            yaml.append("      name: \"").append(id).append("_burn_rate\"\n");
            yaml.append("      page_alert:\n");
            yaml.append("        labels:\n");
            yaml.append("          severity: \"page\"\n");
            yaml.append("      ticket_alert:\n");
            yaml.append("        labels:\n");
            yaml.append("          severity: \"ticket\"\n");
        }
        return yaml.toString();
    }

    /**
     * Writes the Sloth document to a file, creating parent directories.
     *
     * @param file target file; must not be {@code null}
     */
    public void writeTo(final Path file) {
        try {
            if (file.getParent() != null) {
                Files.createDirectories(file.getParent());
            }
            Files.writeString(file, sloth());
        } catch (final IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private static String selector(final String id, final Binding binding, final boolean errors) {
        final StringBuilder selector = new StringBuilder();
        selector.append("slo=\"").append(id).append("\", occurrence=\"first\"");
        for (final Map.Entry<String, String> label : binding.selectorLabels.entrySet()) {
            selector.append(", ").append(label.getKey()).append("=\"").append(label.getValue()).append('"');
        }
        if (errors) {
            selector.append(", outcome=\"failure\"");
        }
        return selector.toString();
    }

    private record Binding(String meterName, Map<String, String> selectorLabels) {
    }

    /**
     * Builder binding each catalog id to its Prometheus meter name.
     *
     * @since 0.1.0
     */
    public static final class Builder {

        private final Map<String, Binding> bindings = new TreeMap<>();
        private String service;
        private SloCatalog catalog;

        private Builder() {
        }

        /**
         * Sets the Sloth service name.
         *
         * @param serviceName service name; must not be blank
         * @return this builder
         */
        public Builder service(final String serviceName) {
            if (serviceName == null || serviceName.isBlank()) {
                throw new IllegalArgumentException("service must not be blank");
            }
            this.service = serviceName.strip();
            return this;
        }

        /**
         * Sets the catalog whose ids must all be bound.
         *
         * @param sloCatalog SLO catalog; must not be {@code null}
         * @return this builder
         */
        public Builder catalog(final SloCatalog sloCatalog) {
            this.catalog = Objects.requireNonNull(sloCatalog, "catalog must not be null");
            return this;
        }

        /**
         * Binds a declared SLO id to the Prometheus meter carrying it.
         *
         * @param sloId          declared SLO id (sanitized form or original spelling)
         * @param meterName      Prometheus meter name, e.g. {@code demo_order_place_seconds_count}
         * @param selectorLabels optional extra selector labels as {@code key, value} pairs
         * @return this builder
         * @throws IllegalArgumentException if the id is not in the catalog, the meter name is
         * blank, or the label pairs are malformed
         */
        public Builder bind(final String sloId, final String meterName, final String... selectorLabels) {
            if (catalog == null) {
                throw new IllegalStateException("set the catalog before binding ids");
            }
            final String id = MetricTagValues.sanitizeTagValue(sloId);
            if (!catalog.ids().contains(id)) {
                throw new IllegalArgumentException("SLO id \"" + sloId + "\" is not declared in the"
                        + " catalog; declared ids: " + catalog.ids());
            }
            if (meterName == null || meterName.isBlank()) {
                throw new IllegalArgumentException("meter name must not be blank for SLO id \"" + sloId + "\"");
            }
            Objects.requireNonNull(selectorLabels, "selectorLabels must not be null");
            if (selectorLabels.length % 2 != 0) {
                throw new IllegalArgumentException("selector labels must be key, value pairs");
            }
            final Map<String, String> labels = new TreeMap<>();
            for (int i = 0; i < selectorLabels.length; i += 2) {
                final String key = selectorLabels[i];
                final String value = selectorLabels[i + 1];
                if (key == null || key.isBlank() || value == null || value.isBlank()) {
                    throw new IllegalArgumentException("selector label keys and values must not be blank");
                }
                labels.put(key.strip(), value.strip());
            }
            bindings.put(id, new Binding(meterName.strip(), labels));
            return this;
        }

        /**
         * Builds the scaffold, requiring every catalog id to be bound.
         *
         * @return an immutable scaffold
         * @throws IllegalStateException if the service or catalog is missing, or any declared id is
         * unbound — the scaffold and the runtime info gauge must never disagree
         */
        public SloScaffold build() {
            if (service == null) {
                throw new IllegalStateException("service is required");
            }
            if (catalog == null) {
                throw new IllegalStateException("catalog is required");
            }
            final TreeSet<String> unbound = new TreeSet<>(catalog.ids());
            unbound.removeAll(bindings.keySet());
            if (!unbound.isEmpty()) {
                throw new IllegalStateException("catalog ids without a meter binding: " + unbound
                        + " — bind every declared id so the scaffold cannot drift from the catalog");
            }
            return new SloScaffold(service, new LinkedHashMap<>(bindings));
        }
    }
}
